# Generated by Django 3.2.8 on 2021-10-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_map', '0002_refreshcycle_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_cycle', models.IntegerField()),
                ('data', models.CharField(max_length=2048)),
                ('score', models.FloatField()),
                ('is_blank', models.BooleanField()),
            ],
        ),
    ]
